### ISSUE TITLE
catching unit

### ISSUE THREAD

**Issue by bam241** [pshriwise/unitBot#3]
when catching unit with more than 1 character it might trigger some single character unit, if there is a character "overlap":
 `1 cm` will trigger `cm to inch`, but also` C to  F` (because of the "c")

**Comment by bam241** [comment]
one solution might be to add the case sensitivity

EDIT: case sensitivity will not work with `mile vs m`

**Comment by pshriwise** [comment]
Maybe there's a setting for exact matching? 

Then hopefully we can use matching strings like "m " and "miles".

**Comment by bam241** [comment]
this should be fixed by #7
