### ISSUE TITLE
Degree symbols causing problems on some machines

### ISSUE THREAD

**Issue by pshriwise** [pshriwise/unitBot#5]
Took a bit for me to realize what the problem was.. Maybe these are only supported in python 3? @bam241 is that what you are using to run/test?

**Comment by bam241** [comment]
@pshriwise I use python3

**Comment by bam241** [comment]
did you fix this with the new printing function ??

**Comment by pshriwise** [comment]
Yeah this should have been taken care of in #6. quantities now provides the unicode versions of those strings for symbols

**Comment by pshriwise** [comment]
#6
